### PR TITLE
Update Gradle Android plugin

### PR DESCRIPTION
**Pull request by lenucksi**
By suggestion of IDEA I've updated the Gradle Android plugin to the most recent version.
Maybe it's useful for more people than me.

Also: This increases the minimum required JDK to 1.8, I've changed the Travis config accordingly.

### CODE REVIEW

**Comment by mendhak** [comment]
I've had a go at this in the past, part of the reason I never finished was the new rearranging required which fails due to 'overlapping prototypes', and I'm unable to sign the APKs.  Every time I try to solve it I am sent down a rabbit hole as Gradle has lots of changes too with `<<` and `.doLast` etc.

Another reason is even though IntelliJ suggests upgrading, it's then unable to receive test events!

image

which leads [here](https://github.com/junit-team/junit5/issues/804) which leads [here](https://github.com/gradle/gradle/issues/1037) 

I suggest leave this upgrading alone until later, the main thing is the signing process but the test results are quite important too considering IntelliJ is the one requesting it

**Comment by lenucksi** [comment]
Thanks for the response - I've have not yet tried to build signed APKs, but good to know that this will likely be an issue.
I'll update the other PR based on the older Gradle config then.

**Comment by mendhak** [comment]
OK I see the problem now from the other PR, I tried compiling on a clean machine and I see Android Studio is requiring a later version of the gradle plugin and zip, just doesn't work without it.  IntelliJ IDEA is working fine.  :weary: 

Let me play around with this a bit. I'll have to move stuff around, there's some deprecation too.

**Comment by mendhak** [comment]
It's merged into master.  I had to split out the assembly+signing task and tests won't work in the IDE.

Strange that the PR didn't auto close. 

https://github.com/mendhak/gpslogger/commits/master

**Comment by lenucksi** [comment]
Thanks, will make the other PR easier to maintain. Weird PR behaviour with this one though. Looks like all changes are present twice in the history now.

**Pull request closed without merging**
