### PR TITLE
Hi! I have made some modifications to a layout adaptation problem

### PR DESCRIPTION
**Pull request by yuhuitech**
Dear developer!

I am the creator of issue #896, and have made some modifications to a layout adaptation problem, which is solved for now. I would appreciate it if you could revise my code and give me some advice. Thank you so much for your time!

Before my modification, here is the screenshot:

copy

Here is the screenshot after my modification. 

copy

### CODE REVIEW

**Comment by franklinbill** [comment]
I agree with this fix method. The text of the positioning part may not need to be so large. : )

**Comment by mendhak** [comment]
I am testing the PR now.  I found that with the largest display size, and largest font size, the text is visible just fine. 
But when I set the display and font size to default, the text is very small now.  

image

I will try to see if there is a way of making it work with default font and display as well.  I am referencing: https://medium.com/over-engineering/making-the-most-of-textview-auto-sizing-on-android-a39f71b6f3af

**Comment by mendhak** [comment]
OK a few more observations.  Actually I think the line added, `android:autoSizeTextType="uniform"` isn't having any effect.  Removing it produces the same result, so the text is just being resized by Android's defaults.  

This is because, it looks like `autoSizeTextType` doesn't apply to EditText, only to TextView.  So to use this step sizing feature will require replacing the EditText with a TextView or TextViewCompat.  I haven't tried this.  

There might be a simpler solution - in the file `src/main/res/values-xhdpi/dimens.xml`, what about changing the value of `simpleview_latlong_textsize` from 44dp to 40dp?  To try this one, undo the changes you've done so far and just change that 44 to 40.

**Comment by yuhuitech** [comment]
Hello! According to your description, I figure it would be better to keep the original size of the text. So I made some changes to make the latitude and longitude scrollable horizontally. It looks good to me. Could you give me some advice on this? Thank you so much. :)

Here is the screenshot after my latest modification:

copy

**Comment by mendhak** [comment]
Sure scroll would be fine, if that's OK with you.  

I'm testing it on a few devices now.

**Pull request merged**
