### PR TITLE
Show altitiude and track details in notifications

### PR DESCRIPTION
**Pull request by CFoltin**
Dear all,

I added some status information to the notification. 
This is useful to get the most relevant trip information without even the need to unlock the phone. 
As we are hiking, I put the altitude as the first information piece. This may be subject for further discussion.
Maybe it useful to add some more strings to the notification line, but then, it is most probable that it is no longer visible in the lock screen.

BR, Chris

### CODE REVIEW

**Comment by CFoltin** [comment]
... and I "fixed" some tests which relied on "." being the decimal separator, which in my german locale is ",".

**Comment by mendhak** [comment]
Hi thanks for the PR, I tested it for a bit.  The notification now looks like this, it is confusing for the user since the first three items aren't immediately obvious as to what they are.  

image

Two options I can think of - it'll be easier on the user if it's just one additional item (altitude) with something like a ▵ to indicate altitude *or* allowing the user to specify the notification format string (with the same parameters as the Custom URL), much more flexible but a lot more work

**Comment by CFoltin** [comment]
Hi, good idea to indicate with a special character. 
Wouldn't it be a good idea to add something like ⌚ for the total time, too? 
Currently, I don't have a good "lightbulb moment" for the total distance. I would drop it, as you suggested.
BR, Chris

**Comment by mendhak** [comment]
This is not going so well.  The title can't accommodate anything more than lat+long on smaller screens.  

Then I noticed the whole unused line below it.  Tried with some of the existing labels, doesn't look elegant but is functional without ambiguity.  Initially I had tried using symbols but in testing noticed that older Android versions don't have all the Unicode characters.  

image

Also tried an InboxStyle with the Notification but it hides the entire summary, only visible when expanding.

Normal:

image

Expanded:

image

**Comment by CFoltin** [comment]
Hi, the visibility without user interaction was the main focus. Thus, the first screen shot looks promising. (Although, personally, I would put it the other way round, because I'm not interested in the current coordinates at all. But, there may be other use cases in which one need them. Perhaps, you can tell me about that?). Can you commit your changes here? TIA, Chris

**Comment by mendhak** [comment]
Pushed to your repo, have a look. 

What goes in the notification will be different for everyone, trying to look for some lowest common denominator.

**Comment by mendhak** [comment]
image

**Comment by mendhak** [comment]
Using `Html.fromHtml` - 

image

image

**Comment by CFoltin** [comment]
Bug fix pushed.

**Comment by CFoltin** [comment]
Although, I know, that it may be a matter of preferences, but I would prefer to have the total time before the accuracy. The accuracy doesn't change very much (at least in my case), and the total time is relevant for many situations, IMHO.

**Comment by mendhak** [comment]
Like this:

image

**Comment by CFoltin** [comment]
Excellent, thanks!

**Comment by mendhak** [comment]
v89 released to market

**Pull request merged**
