### PR TITLE
Request focus for annotation text box on open

### LINKED ISSUE #841: Annotation input not focused
When the pen button clicked, annotation popup is opened, soft keyboard is shown, but seems like the input focus is not set to the textbox. Direct typing will go nowhere and explicit tap on a textbox is required to put there cursor and do input.

### PR DESCRIPTION
**Pull request by yrtimiD**
Fixes #841 
The fix is simple and dirty but works (tested)

### CODE REVIEW

**Comment by mendhak** [comment]
This works from the main view.  Problem - when I clicked Annotate from the notification, I got this error:  

```
2021-08-16 19:58:44.784 8773-8773/com.mendhak.gpslogger E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mendhak.gpslogger, PID: 8773
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mendhak.gpslogger/com.mendhak.gpslogger.NotificationAnnotationActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:907)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1577)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1424)
        at android.widget.ListPopupWindow.show(ListPopupWindow.java:715)
        at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1316)
        at com.mendhak.gpslogger.ui.Dialogs$9.onFocusChange(Dialogs.java:304)
        at android.view.View.onFocusChanged(View.java:7808)
        at android.widget.TextView.onFocusChanged(TextView.java:10779)
        at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1172)
        at android.view.View.handleFocusGainInternal(View.java:7478)
        at android.view.View.requestFocusNoSearch(View.java:12441)
        at android.view.View.requestFocus(View.java:12415)
        at android.view.View.requestFocus(View.java:12382)
        at android.view.View.requestFocus(View.java:12324)
        at com.mendhak.gpslogger.ui.Dialogs.autoCompleteText(Dialogs.java:313)
        at com.mendhak.gpslogger.NotificationAnnotationActivity.onCreate(NotificationAnnotationActivity.java:48)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2021-08-16 19:58:44.797 8773-8773/com.mendhak.gpslogger I/Process: Sending signal. PID: 8773 SIG: 9

```

**Comment by mendhak** [comment]
Try this, it seemed to work for me?

```
        alertDialog.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override
            public void onShow(DialogInterface dialog) {
                customAutocomplete.requestFocus();
            }
        });

```

**Comment by yrtimiD** [comment]
@mendhak , oops, completely forgot about option to annotate from notifications!
Thanks, your code is way better and works in both cases! Sorry for dragging you into this fix :)

**Comment by mendhak** [comment]
No worries, I'm just going to merge this and set up a tag so that F Droid can pick it up.

**Pull request merged**
