### PR TITLE
[WIP] Attempt #524 Record Sensor Data

### PR DESCRIPTION
**Pull request by lenucksi**
Thank you for your hints in #524. I've created this branch to see what I can do about it. Since I'm not that experienced with Android stuff I might have a few more questions for you.

Also, as long as this is [WIP] it's not ready to be merged yet.

### CODE REVIEW

**Comment by mendhak** [comment]
Hey good start.  Just wanted to make a few comments to start so you don't go down a rabbit hole; I'd suggest changing [Vector](http://stackoverflow.com/questions/1386275/why-is-java-vector-class-considered-obsolete-or-deprecated) to ArrayList

My main concern is always battery drain, so I will want to test this running over a long period, not to sound dismissive but if it does prove to be a battery drain I don't want to merge it!  

I can see the `/10` in the handler, this will end up still causing greater battery drain.  Better to put the logging interval in the `registerListener`, also unregister it when not being used, this is because the act of asking for sensor updates is a partial wakelock.

**Comment by lenucksi** [comment]
Thank you for your input, especially on the battery consumption issues. My current approach was to just hook up a large external battery pack, but surely there are better approaches.

The research question requires to fetch GPS data points with an interval of about 2 to 5 seconds, and record multiple intermediate sensor data points. Currently the maximum length of one recording session was about 6 to 8 hours, in average it is likely to be around 5 hours.

In a completed state I would like the PR to allow disabling the sensor data recording, maybe customising the sensor data recording frequency similar to the GPS recording frequency. It might also be interesting to be able to treat compass and accelerometer differently.
Also data could be shown in the UI and needs to be exportable upon completion of the recording along with some hand-entered data.
If disabled the function should not consume any additional energy I would hope - but from what I've seen in the Android documentation this needs proper management of the listeners and sensor configuration. I'm usually not an Android developer, so I'll have to read up on all these things.

**Comment by lenucksi** [comment]
Yet another case of GitHub PR running wild. It's just my two changesets. Feel free to delete the PR and I'll open up another one.

**Comment by lenucksi** [comment]
As of 8a1fc7c this is the most current version I have been testing with.
The battery test results mentioned in #524 are done on this basis.

**Comment by lenucksi** [comment]
I've merged in the most recent master, let's see what I can do about the tests. They look like mostly GPX/KML based failures.
Other than that, you could also ignore the last two change sets.

**Comment by mendhak** [comment]
My mistake - I had started commenting in the wrong thread then just kept it going.  I've been trying to catch up with all the information you've given.  

@lenucksi please forgive me, can you stop this PR.  

I will explain.  Having gone through your latest comments and understanding things a bit better now (it's taken me all this time), I feel that sensors are not a good match for this GPSLogger app.  I had naively assumed they would behave just like a simple location manager - read something and rest.  I should have spent a little time understanding how they worked before encouraging this ongoing work.  I can also see that any compromises you keep making to suit my "GPSLogger way" will not be of a good quality that users will want over time.  It also makes sense to me now why sensor recording apps are standalone on the play market, I had thought that if GPS and Sensors go together why hadn't they done it too.  The code flows are different and I can see over time that this will take over a major part of the workflow.  Normally I do research on these topics beforehand but in my excitement I neglected it.


I've been reading through [this](https://github.com/blog/2124-kindly-closing-pull-requests) all day today to see how to write this message... but I am hoping you will understand my explanation.  

I might as well mention - for the testing, my devices are:  One Plus One, One Plus 3T, Nexus 5, Nexus 5X, Moto G, Google Pixel - the debug logs gave me nothing, they simply stopped.   But today the OnePlus One was the only device where the app wasn't killed.    The only weird thing about it - it has LineageOS (formerly CyanogenMod before their strange shutdown last year).

**Comment by lenucksi** [comment]
> @lenucksi please forgive me, can you stop this PR.

Yes I can, and thank you for the explanation.
However, since the PR already provided very useful results for me and I'll need a lot more data to come I'll maintain it in my fork of your repo.

For that reason I would like at some point be able to publish the fork to the play store or some other location that allows for easy installation. Since I would like to avoid confusion with your app to keep people from expecting the wrong things from either of them I'd appreciate help from you to create and maintain a reasonable distinction between the original GPSLogger and a let's say "SensorAndPositionLogger".

I will likely change a few more things, such as e.g. #299, and would be happy to have code moving in both directions where it's useful for both parts.

> I've been reading through this all day today to see how to write this message... but I am hoping you will understand my explanation.

I did not know GitHub has advice on that, good to know that they have it though. :)


> I might as well mention - for the testing, my devices are: One Plus One, One Plus 3T, Nexus 5, Nexus 5X, Moto G, Google Pixel - the debug logs gave me nothing, they simply stopped. But today the OnePlus One was the only device where the app wasn't killed. The only weird thing about it - it has LineageOS (formerly CyanogenMod before their strange shutdown last year).

Thanks. I guess I have access to a Moto G and some One Plus phones as well. Maybe I'll see if I can reproduce that.
Which versions of Android and variants do the other phones have? And which version of LineageOS does the One Plus One have?
And it looked like the service as well as the activities were just killed - did you see any ANR notifications or anything else before thing got killed? How long did the app last before it was killed?

**Comment by mendhak** [comment]
Thanks for understanding.  Yes it's a good idea since you are learning these many things, main thing to remember is to change the package name of the APK - Google Play Store will block if the package is `com.mendhak.gpslogger`

The OPO has LineageOS May 30 Nightly, Nexus 5 has Android 6, Nexus 5X and MotoG has Android 7.0, OP3T has Android 7.1.1

From the logs I see about 30-70 minutes before the app gets killed, without error.  Do you see that too?  No ANRs though.  Are you seeing any battery warning messages?

**Pull request closed without merging**
