### PR TITLE
last position of yesterday is first of today

### PR DESCRIPTION
**Pull request by ciakpey**
Check if we change of day and then write the last position of yesterday as the first position of today

### CODE REVIEW

**Comment by mendhak** [comment]
Hi, had a look at this. `ResetCurrentFileName` [gets called](https://github.com/ciakpey/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L803) before writing to file anyway.  So this check shouldn't be needed.

**Comment by ciakpey** [comment]
Hi,
I knwo, in fact currently the app first try to get a point that match 
the filter distance and the accuracy filter
so If you stay at the same place during one day, no point will be 
recorded during the day, and so the file of the day won't exist.

With my check, as soon as we change day, I write the last known point 
for the new day, so if we stay at the same place during the day, the log 
file will contain one point.

**Comment by mendhak** [comment]
I was so busy for 2 months :weary:  At last I've been able to merge.

**Comment by mendhak** [comment]
v70 released and will appear in market in a few hours. Thanks again

**Pull request merged**
