### PR TITLE
Optimize energy usage when activity recognition is enabled

### PR DESCRIPTION
**Pull request by zhao-gang**
Stop GpsManager if activity recognition option is enabled and user is still for a long time.

Currently location listener isn't removed when user is still and activity recognition is enabled. This patch tries to reduce energy usage by removing location listener in above situation.

I removed the `userHasBeenStillForTooLong` check from `startGpsManager`, so `startGpsManager` will always register the location listener(if not already registered). So I think it's not needed to set an alarm with  `setAlarmForNextPoint`. As GpsManager will be started through `activityRecognitionEvent` event handler.

### CODE REVIEW

**Comment by mendhak** [comment]
I have been testing this on its own but I'm finding that the setAlarmForNextPoint is kicking in and the logging resumes as normal, so the saving is minimal.  I also tried with-and-without but not seeing much of a battery saving, are you seeing any.  Interested to hear what you are observing when you run this?

**Comment by mendhak** [comment]
(removing due to cleanup)

Google Drive and Activity Recognition features have been removed so I'll close this PR as the target feature no longer exists

**Comment by andreapx** [comment]
I was going mad looking for this activity recognition on the app!!! @mendhak would you be so kind to remove it from https://gpslogger.app/ ? Thanks a lot!

**Comment by mendhak** [comment]
Ah I missed that.  I've now removed references to Activity Recognition and Drive.  It'll still be there in some screenshots.  But I've also added a FAQ item about why they were removed.  

The gpslogger.app site should update soon I think.

**Pull request closed without merging**
