### PR TITLE
Add GeoJSON logger

### PR DESCRIPTION
**Pull request by agp8x**
This adds support for logging to GeoJSON.
For my usecase, having a list of Points is acceptable, as LineStrings only support coordinates, and nested FeatureCollections are not standard conform.

To get Android Studio to compile the project I had to slash a bit around in the gradle files :)

### CODE REVIEW

**Comment by lenucksi** [comment]
That's a nice addition. :D I also whacked around in the Gradle files, see #537. @mendhak also had something to say on Gradle bugs due to the update - can you have a look and see if you can confirm them?

**Comment by mendhak** [comment]
master branch has been updated with the 'latest' - can @lenucksi @agp8x get latest from master this should prevent you having to fiddler around with gradle stuff.

**Comment by agp8x** [comment]
Thanks for the update, now it works properly :)

**Comment by mendhak** [comment]
OK I am testing this now.  I've had a skim through GeoJSON and I can see why FeatureCollection was chosen it's the closest way of getting a track log with some 'meat' on it.  It also appears to allow for metadata so in the future other bits of info can be added in like hdop vdop or whatever is needed.   

Few things:

- [ ] I noticed the file is written in a single line, please add a newline after each written line, I think would be in the `TEMPLATE` 
- [ ] A few of the classes appear to be unused `GeoJsonwriterfeaturecollections` and `geojsonwriterline`, can be removed
- [ ] The `GeoJsonWriter` interface doesn't seem to be necessary, may have been used during testing but also can be removed
- [ ] The icon for geojson isn't appearing for me in simple view does it appear for you? 
- [ ] Some tests around the generated strings/templates would be useful; from experience I find that loggers tend to break the most over time and tests covering the string generation help keep things steady

Also a few more things I'll have a look at 

- [ ] Annotate button not active when geojson is the only logger
- [ ] Need to test with uploading to various sources

**Comment by mendhak** [comment]
Pushing latest master directly to your repo, replaced the geojson icon with a simple '.json' icon and made it show on the simple logging screen. 

I hope you're not being blitzed with lots of Github notification emails.  Sorry if you are.  Tough it out.

**Comment by mendhak** [comment]
v89 released to market

**Pull request merged**
