### PR TITLE
Fix preference spacing

### PR DESCRIPTION
**Pull request by TacoTheDank**
This should fix the preference spacing issue that came up due to https://github.com/mendhak/gpslogger/pull/913

Also I reformatted the XML files because they looked really bad.

### CODE REVIEW

**Comment by mendhak** [comment]
Hi sorry but I was looking to keep the larger font sizes on the preference screens.  Unless, there's some reason not to keep it... accessibility maybe, I suppose I should stay consistent with other apps so that users get to pick their display/font sizes?  What do you think?

This is what I want to keep, the titles are larger, and reduced padding.  
I realize the look has appeared through happenstance, but I liked it,  so I want to keep it until it I lose it some day.  

image

I did try applying your branch, but all the text becomes smaller:

image




The other thing is I wanted to avoid is adding the  `iconSpaceReserved` to every single preference. It feels like a bandaid solution to some underlying problem.  This way is also hacky but is one place to do it:  https://stackoverflow.com/a/52960668/974369

res/values-sw360dp-v13/values-preference.xml:

```
<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:tools="http://schemas.android.com/tools">
    <bool name="config_materialPreferenceIconSpaceReserved" tools:ignore="MissingDefaultResource,PrivateResource">false</bool>
    <dimen name="preference_category_padding_start" tools:ignore="MissingDefaultResource,PrivateResource">0dp</dimen>
</resources>

```

**Comment by mendhak** [comment]
>  I suppose I should stay consistent with other apps so that users get to pick their display/font sizes? What do you think?

Hey I thought on this more, I think yes, let the users' device decide, what we can do is provide some consistency so when they increase the font/display size in one place, it's the same for all their apps. I had become too enamoured with the larger preference titles.

**Comment by mendhak** [comment]
Thanks! Merged it now. I'll include it with the next release (after v118) but no idea when that is.  Currently the F-Droid servers seem to be breaking due to the [Let's Encrypt CA Expiry](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/)

**Comment by TacoTheDank** [comment]
Thanks!

**Pull request merged**
