### PR TITLE
ownCloud upload

### PR DESCRIPTION
**Pull request by codeling**
Adds the capability to upload tracks to ownCloud via the (slightly modified) official owncloud-library (https://github.com/owncloud/android-library).

The code is tested, but only on one device (LG Nexus 5), and not specifically for error conditions, will hopefully be able to do that in the next few days.

### CODE REVIEW

**Comment by codeling** [comment]
As far as I can see the build currently fails because of some issues with the old httpclient library required for the ownCloud library. I will see what I can do about that in the next days.

For now, I have put up a debug apk package of the gpslogger here: https://codeling.bfroehler.info/gpslogger-debug.apk

**Comment by codeling** [comment]
As far as I can see the build currently fails because of some issues with the old httpclient library required for the ownCloud library. I will see what I can do about that in the next days.

For now, I have put up a debug apk package of the gpslogger here: https://codeling.bfroehler.info/gpslogger-debug.apk

**Comment by codeling** [comment]
As far as I can see the build currently fails because of some issues with the old httpclient library required for the ownCloud library. I will see what I can do about that in the next days.

For now, I have put up a debug apk package of the gpslogger here: https://codeling.bfroehler.info/gpslogger-debug.apk

**Comment by codeling** [comment]
As far as I can see the build currently fails because of some issues with the old httpclient library required for the ownCloud library. I will see what I can do about that in the next days.

For now, I have put up a debug apk package of the gpslogger here: https://codeling.bfroehler.info/gpslogger-debug.apk

**Comment by codeling** [comment]
Not sure about the exact reason of the build failure - locally, for me the build works without a problem! The only message that is given in the FAILED section in the Travis CI build linked to above is the warning about the ignored inner classes. Why is this a failure there but not in a local build? Anybody care to comment? @mendhak maybe do you have some pointers? Is it a requirement to drop the commons.httpclient reference for this to work?

**Comment by mendhak** [comment]
I'll investigate why the build is breaking, it may be a simple command to stop pre-dexing, no worries about that.

You mentioned a modified version of the OwnCloud Android library - is this modification necessary?  I'd rather keep in cycle with the OwnCloud Library Releases so that it isn't another maintenance piece.  

I also noticed you added an `.aar` as well as a reference to their maven, are they both used?

You can see that my reply(replies) are very delayed, so it may be a while before I am able to properly merge.  I do appreciate that you created a PR! :smile:

**Comment by codeling** [comment]
> I'll investigate why the build is breaking, it may be a simple command to stop pre-dexing, no worries about that.

Thanks! This is beyond my current android skills to investigate :|.

>You mentioned a modified version of the OwnCloud Android library - is this modification necessary? I'd rather keep in cycle with the OwnCloud Library Releases so that it isn't another maintenance piece.

The changes that I did are those reported here: https://github.com/owncloud/android-library/issues/64
(making one method public).

> I also noticed you added an .aar as well as a reference to their maven, are they both used?

I'm not really firm with the gradle build system. I thought what I added in the build.gradle was a reference to the aar file.

**Comment by mendhak** [comment]
OK no worries, I can investigate that. Even if it's beyond your current Android skills, your PR is quite nice and clean and easy to go through.

**Comment by codeling** [comment]
> Even if it's beyond your current Android skills, your PR is quite nice and clean and easy to go through. 

Thanks. Been writing Java for a while, just the current android platform is not familiar to me ;).

> You can see that my reply(replies) are very delayed, so it may be a while before I am able to properly merge. I do appreciate that you created a PR! :smile:

I will try to update the branch to reflect the latest master changes

**Comment by mendhak** [comment]
I've merged your changes with master into [this branch here](https://github.com/mendhak/gpslogger/tree/codeling-ownCloudUpload).

I figured out why you made those changes in the OwnCloud Library but I believe I've handled the things you were trying to solve, but some problems too.  Some points:

### Changes

* It is possible to have a [Handler in a background thread](https://github.com/mendhak/gpslogger/blob/codeling-ownCloudUpload/gpslogger/src/main/java/com/mendhak/gpslogger/senders/owncloud/OwnCloudJob.java#L83) by using a `Looper`
* I have [access to a Context](https://github.com/mendhak/gpslogger/blob/codeling-ownCloudUpload/gpslogger/src/main/java/com/mendhak/gpslogger/senders/owncloud/OwnCloudJob.java#L91) by using `AppSettings.getInstance()` because `AppSettings` extends `Application`
* The class implements [OnRemoteOperationListener](https://github.com/mendhak/gpslogger/blob/codeling-ownCloudUpload/gpslogger/src/main/java/com/mendhak/gpslogger/senders/owncloud/OwnCloudJob.java#L33), so that it can handle [onRemoteOperationFinish](https://github.com/mendhak/gpslogger/blob/codeling-ownCloudUpload/gpslogger/src/main/java/com/mendhak/gpslogger/senders/owncloud/OwnCloudJob.java#L119). 

I also had to add `org.apache.jackrabbit` to the application in [build.gradle](https://github.com/mendhak/gpslogger/blob/codeling-ownCloudUpload/gpslogger/build.gradle#L181), else the exception was throwing an exception :laughing:   Unfortunately I ended up hitting the [Android 65K limit](https://developer.android.com/tools/building/multidex.html) so it took a while to trim down the app to accommodate all these extra libraries. 

### Testing

Now what I am trying to do is, I've signed up on [blaucloud.de](https://www.blaucloud.de/en/singup-and-product-table) for a free OwnCloud instance.  However, it seems to fail.  

> 07-04 18:17:02.731  29842-32300/com.mendhak.gpslogger D/OwnCloudClient #2﹕ Creating OwnCloudClient
07-04 18:17:02.732  29842-32301/com.mendhak.gpslogger D/OwnCloudClient #2﹕ REQUEST PUT /remote.php/webdav/gpslogger/gpslogger_test.xml
07-04 18:17:02.733  29842-32301/com.mendhak.gpslogger D/AdvancedSslSocketFactory﹕ Creating SSL Socket with remote nomnom.blaucloud.de:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@137b38ee
07-04 18:17:02.733  29842-32301/com.mendhak.gpslogger D/AdvancedSslSocketFactory﹕ ... with connection timeout 60000 and socket timeout 60000
07-04 18:17:10.482  29842-32300/com.mendhak.gpslogger E/OwnCloudJob﹕ onRemoteOperationFinish:122 - Local file does not exist

Not sure what that error means, but I dug a bit through the Owncloud Android library and this seems to indicate that a file doesn't exist on the server, as it's a remote operation result.  So it might be a problem with blaucloud, possibly?  Have you ever seen that?

### TODO

I want to change the server textbox to Base URL.  Some people may have OwnCloud on `http://example.com:9191/owncloudx`

**Comment by mendhak** [comment]
Never mind that error - I had to create the 'gpslogger' folder in OwnCloud first.  I just assumed it would be created, oops.

**Comment by mendhak** [comment]
String localizing and cleanup done. 
Server textbox changed. 
Mimetype field is not used, so I blanked it.

Now a bit of testing over the next week.  I'll merge it into master later.  Thanks a lot!

**Comment by codeling** [comment]
Thanks a lot for picking up where my skills ended ;)!

**Comment by codeling** [comment]
Tested the codeling-ownCloudUpload branch a bit, seems to work - but only the debug build, is that normal? When I try to install the gpslogger-release-unsigned.apk I get the message "Parsing error - There was a problem parsing the package" (I translated this from german) on my LG Nexus 5 device.

**Comment by mendhak** [comment]
The debug APK is usually signed by your debug certificate.  You can find it at `~/.android/debug.keystore`

A release-unsigned APK is meant to be signed by your own certificate.  It's in limbo, waiting for you to sign it. But one way or the other, you can't install an unsigned APK.  It has to be signed by something.

This branch is now merged into master.  I'm going to make the release APK now.

**Comment by mendhak** [comment]
Released to play store.  Thanks for your contribution.

https://github.com/mendhak/gpslogger/releases/tag/v65

**Pull request closed without merging**
