### PR TITLE
Ticket #299: Provisioned Profiles

### PR DESCRIPTION
**Pull request by lenucksi**
Adds an activity with a matching intent filter that does the following:
 - If an URL presenting a `application/sensorgpslogger` mime typed file is opened in a browser GPSLogger is opened and downloads the file to the profile storage directory.
 - GPSLogger then tries to switch to the profile name given by the filetype.
 - This is supposed to allow easier provisioning of settings for users by providing them with a simple URL.

### CODE REVIEW

**Comment by alexuvero** [comment]
Hi, I use this application about a year ago, and I would like it if it were possible and you believe it will have a new function, if I have a missed call, that is, I only call the mobile, the apk gpsloger send me a message text (sms) to the number from which you received the call with some data,
1 coordinates where you are at that moment
2 battery charge
3 speed and de-troweling
an SMS that does not exceed 70 characters.
this functionality is very useful in case of mobile theft, or in my case I use a cell phone installed in my car as gps. you do not see the importance of that functionality, because the apk is not designed for that, and in your country it is very easy to buy a gps for the car and have follow-up in real time and all that but I live in Cuba, there are no stores where to buy that, the internet is expensive, you can not pay anything online because we do not have credit cards, the sites do not deliver to Cuba by customs laws, the internet in mobile phones by 3G still does not work well, also of other things that you would not mind. I use today in the mobile phone that I have as GPS three applications for the correct operation. (gpslogger) to generate the gpx file, (wifi explorer) to connect via wifi to the mobile from my pc and copy the file that (gpslogger) generated me, and an apk I develop a cuban, (dondeando) to give the missed call and to return the sms with the location. as you see I have two apk using the gps that can create conflict and use exesibo battery consumption, thank you excuse the inconvenience and I would appreciate it if you at least value my request. Sincerely Alexander Angulo Gomez ---- alexuvero01@gmail.com

**Comment by lenucksi** [comment]
a) there are likely quite a few theft prevention / beacon apps for exactly that purpose
b) this is a PR for a specific purpose, not an issue. Put this into a separate issue for @mendhak to consider.
c) it is not recommended to publicly expose your email address, you'll be subject to SPAM easier that way...

**Comment by StephenAtty** [comment]
I think this would be a very useful addition to the application.

**Comment by StephenAtty** [comment]
Actually can't you do it by using an Android Application link

For example I know that if you had Backitude installed and the browser on your phone was passed a url looking like:

com.gaugler.backitude://preferenceImport/?prefs=url_to_config_file

then it automatically downloaded it and installed it.

Which means you can use the same code to generate the config file for manual or automatic installation.

**Comment by mendhak** [comment]
*Two years later*

It took a little while but I've been able to work on this a bit now.  I had wanted to start with your branch as a base but the direction I went was just not the same - so unfortunately it will mean I'm going to close this PR and direct you to #760 .  

But I did leave the PR open for so long because it was my reminder to actually get this done in some form, so I do thank you for the inspiration. :grin: 

https://github.com/mendhak/gpslogger/pull/760

**Comment by mendhak** [comment]
v103 released to market

**Pull request closed without merging**
