### PR TITLE
Add a view with buttons to add different annotations by button press

### PR DESCRIPTION
**Pull request by bluehazzard**
# Introduction
I used this app for a lot in the last weeks, but needed a way to quickly add annotations. The implemented way is not really fast and if you search in the issues, you can find quite some other people who needed this as well  like #277 
This is an open source project so i thought, why not implement it by myself. Note: this is my first App programming, and i do not know anything about UI in android, so if you find some things that are not the android way, do not hesitate to criticize. 

# Instruction
This pull request adds a new view in the drop down selector
image
In this view a grid of 3x3 Buttons is displayed. If you press one of the buttons an annotation event is triggered and the text of the button is saved as annotation.
image
the text and the colour of the button can be customized by a long press on the button
image

# Implementation details
The buttons are hard coded, it would be possible to make it customizable and create the buttons programmatically, but i was not sure how the UI for this should look like, and it would probably be a lot of work, that i did not had the time to implement. For me it was important to have 9 buttons, that are easily pressable, and so a i came up with this UI
The layout is not perfect, you can see that the bottom bar is overwriting the bottom button row, but i am no expert and do not know how to fix this.
The settings are stored as JSON string, so it would be easy to make the button count dynamic... I do not know if this is the right way to do, but it is easy and fast...
I added the dependency "androidx.constraintlayout:constraintlayout", i have not looked what minimal android version this needs, and what the minimal version this app supports, but the forum posts i read for this implementation are quite old, so i was thinking this should be fine...

Any comments and critique is welcome

### CODE REVIEW

**Comment by mendhak** [comment]
Thanks I'm having a look through this right now, it does seem somewhat straightforward.  I'm tinkering about and trying the same 'progress' button as the simple view.  Paired with the `updateButtons` method and it creates some visual feedback. 

[untitled.webm](https://user-images.githubusercontent.com/746276/210092735-ea01e477-fc48-479a-8c27-7898a488b0e8.webm)

**Comment by mendhak** [comment]
Changed the color text to use a color picker

[colorpicker.webm](https://user-images.githubusercontent.com/746276/210104347-dcf4a137-12b3-4b60-9b0e-c9ff55b80261.webm)

**Comment by bluehazzard** [comment]
Nice work so far!

**Comment by mendhak** [comment]
I've made a change, the buttons won't be disabled when one is pressed.  The user can click other buttons and that will be the annotation that's going to be written once a log point is available.  

[many_buttons.webm](https://user-images.githubusercontent.com/746276/211103457-05a0a815-fe2a-4ab8-afde-94bec7424f28.webm)



I've also added a feature, when a user switches profiles, the buttons reload. 

[switch_profile.webm](https://user-images.githubusercontent.com/746276/211103478-3c7985ba-5258-4400-bd8f-5b7c0416f6d0.webm)

**Comment by mendhak** [comment]
Merging this into branch 126, not into master just yet.  I'll be adding a few more features and fixes etc.

**Comment by mendhak** [comment]
v126 is now in [releases](https://github.com/mendhak/gpslogger/releases/tag/v126) and [fdroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/).

**Comment by bluehazzard** [comment]
Great work! Thank you!

**Comment by bluehazzard** [comment]
I think you can close https://github.com/mendhak/gpslogger/issues/277 now

**Comment by mendhak** [comment]
And thanks to you for starting it.  Good point I'll close that issue.

**Pull request merged**
