### PR TITLE
Let GpsLoggingService be foreground only when logging

### PR DESCRIPTION
**Pull request by zhao-gang**
It's better to show logging notification when it's actually logging.

### CODE REVIEW

**Comment by mendhak** [comment]
Thanks for raising this.  I've been trying to remember why I added that in https://github.com/mendhak/gpslogger/commit/ea52ecf99ae001d5907afe5fe13617eb74e86312

I do  recall the application crashing soon after opening it, due to a restriction - [as described here](https://stackoverflow.com/questions/45525214/are-there-any-benefits-to-using-context-startforegroundserviceintent-instead-o).  I think I was trying to get automation apps working with this but it simply wouldn't work without starting as foreground service (since it's being invoked in the background).  

This will need testing, I am not 100% confident in the consistency of Android's service-forgiveness across releases, or [the current implementation even if you do things properly!](https://issuetracker.google.com/issues/76112072).  

It would help if you can mention which features you have tested it with, eg regular use, regular logging, automation, bootup logging, etc.   I'll be trying it out with as many features as I can as well

**Comment by zhao-gang** [comment]
I tested this PR on API level 27 with `targetSdkVersion` 28, Automate sometimes can't start GPSLogger. The problem is described in https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground

It seems the only way to solve above problem is to change the `targetSdkVersion` to 25.

**Comment by mendhak** [comment]
I'm getting that too, the application will ANR with the same complaint as you found, I think this is why I had originally introduced the startForeground even on app open.  

Google Play Store isn't allowing v25 any longer, we have to target v26 minimum, and from November it has to be v28.   So this problem will come back anyway.

**Comment by mendhak** [comment]
So I had to leave this out of v101, in my testing I was getting ANRs and also when running the app it was being killed more frequently than in the original version.  I need to understand this better.  If starting as foreground from the start is helping with the app's stability I'd like to keep the original.  But if the ANRs are a coincidence then this pull request is simply a cleaner way of managing the foreground service

**Comment by mendhak** [comment]
I've been testing this a few days and it looks OK now, I'll merge it.  Hopefully no problems, but if problems reoccur I'll have to revert it.  Fingers crossed, no need to do that

**Comment by mendhak** [comment]
v102 pushed to market

**Pull request merged**
